FROM mysql:8.0

COPY etc/mysql/conf.d/charset.cnf /etc/mysql/conf.d/charset.cnf
RUN chmod 644 /etc/mysql/conf.d/charset.cnf
COPY etc/mysql/conf.d/log.cnf /etc/mysql/conf.d/log.cnf
RUN chmod 644 /etc/mysql/conf.d/log.cnf
